### PR TITLE
GLPI 10.0 compatibility

### PR DESCRIPTION
**Pull request by cedric-anne**

### CODE REVIEW

**Comment by stonebuzz** [comment]
read only field seems broken 
image

**Comment by stonebuzz** [comment]
Drag and drop icon misplaced (also while moving an element)

image

**Comment by stonebuzz** [comment]
bad css for save button (add tab type)
image

**Comment by VladoTTX** [comment]
Checked 10.0.0-rc2 with fields 1.13.0-rc2 and issue with read-only fields as reported by @stonebuzz still exist. Let me know whether I should open new issue or is it OK to report here.

I've tested all the field types.

These RO fields does not work completely:
- Date
- DateTime

It is possible to save them regardless of "Read Only" setting in field setup.

Issue is also with Users field. If set to RO it is not displayed in container at all but after container saving it contains value "Myself".

Also I've noticed that behavior of "Number" field changed. In 9.5.x version in allowed to enter floating point. Now it is not possible, just whole numbers are accepted, Feature or bug?

image

Also if whole container is set as Read Only for given profile some fields are editable (you are just not able to save them):
- Text Area
- Date
- DateTime

**Pull request merged**
