### PR TITLE
Implementation of multiple choice dropdowns 

### PR DESCRIPTION
**Pull request by Aeto-J**
Hello, 
- Implementation of multiple choice dropdowns
- Implementation of default value for dropdowns (single or multiple choice)
- Add default values to the fields defined on a tab other than the main one, during object creation (to be sure that default values will be always present for queries)

Thank you
best regards
Aeto-J

### CODE REVIEW

**Review by tomolimo — APPROVED** [review]
Seems ok for me

**Comment by cedric-anne** [comment]
Hi,

As this PR is handling 3 distinct changes, please split it into 3 PRs, so it would easier to validate:
- Adding multiple dropdown feature (with its default value handling)
- Enhancement of single dropdown default value handling.
- Enhancement of default values handling on object creation.

Some remarks about the proposed code.

1. Adding a `multiple` option on database, `Container::addField()` and `Migration::getSQLFields()` for just one field type does not seems the best option. Maybe `dropdown_multiple-*` types should be introduce.
E.g.
```diff
diff --git a/inc/field.class.php b/inc/field.class.php
index 70f2d1a..1909769 100644
--- a/inc/field.class.php
+++ b/inc/field.class.php
@@ -1263,7 +1263,8 @@ JAVASCRIPT
         foreach (PluginFieldsToolbox::getGlpiItemtypes() as $section => $itemtypes) {
             $all_types[$section] = [];
             foreach ($itemtypes as $itemtype => $itemtype_name) {
-                $all_types[$section]['dropdown-' . $itemtype] = $itemtype_name;
+                $all_types[$section]['dropdown-' . $itemtype] = sprintf(__('%s (unique value)', 'fields'), $itemtype_name);
+                $all_types[$section]['multiple_dropdown-' . $itemtype] = sprintf(__('%s (multiple values)', 'fields'), $itemtype_name);
             }
         }
```

2. A json string limited to 255 chars to store multiple value may be too limited. A solution would be to increase the `VARCHAR` length, but a too high value may cause issues if user wants to use multiple fields of this type, as it will probably reach the MySQL row size limit. The best solution is to use a `TEXT` field here.

3. Default values should display items name (using `getDropdownName()` maybe), instead of raw values:
image

4. When editing something else than a dropdown, the "multiple dropdown" option should not be displayed.
image

**Comment by cedric-anne** [comment]
I reverted the merge, there are too many points to fix.

**Comment by tomolimo** [comment]
ok, we'll will see your remarks and we'll post new PR
Thank you
Regards,
Tomolimo

**Pull request merged**
